disabled_rules:
    - force_cast
    - vertical_parameter_alignment
    - trailing_whitespace
excluded:
    - Pods
    - fastlane
    - Carthage

function_body_length:
  warning: 70
  error: 120

line_length: 130
