name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      #run: swift build -v
      run: xcodebuild clean -scheme SmartWallet -destination $DESTINATION -derivedDataPath $DERIVED_DATA_PATH build-for-testing
    - name: Run tests
      run: swift test -v
