name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: macos-latest
    env:
      SCHEME: "SmartWallet"
      DEVICE: "iPhone 11"
    steps:
    - uses: actions/checkout@v2
#     - name: clean
#       run: xcodebuild clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE"
#     - name: Upload products
#       uses: actions/upload-artifact@v1
#       with:
#         name: Products
#         path: SmartWallet/artifact
    - name: test
      #run: xcodebuild -workspace SmartWallet.xcworkspace -scheme $SCHEME -sdk iphonesimulator -destination 'platform=iOS Simulator,name=$DEVICE' test
      run: xcodebuild -workspace SmartWallet.xcworkspace -scheme "SmartWalletUITests" -sdk iphonesimulator -destination 'platform:iOS Simulator, id:F78F0EE7-FF1E-4AA6-96D3-5877E4D3F476, OS:13.6, name:iPhone 11' test



