name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      SCHEME: "SmartWallet"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
#       UNIT_TEST_TARGET: "SmartWalletTests"
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_11.3.app
    - name: clean
      run: xcodebuild clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE"
#     - name: Upload products
#       uses: actions/upload-artifact@v1
#       with:
#         name: Products
#         path: SmartWallet/artifact
#     - name: test
#       run: xcodebuild test-without-building -project SmartWallet.xcodeproj -scheme "SmartWalletUITests" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.6" 
      #run: xcodebuild -workspace SmartWallet.xcworkspace -scheme "SmartWalletUITests" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=13.6" test-without-building

